### ISSUE TITLE
priceRatio can be null

### ISSUE THREAD

**Issue by blake-regalia** [securesecrets/shadejs#77]
**Describe the bug**
Unable to perform swap calculations on stable pool when the contract returns `null` for `get_pair_info.stable_params.p`, which can happen according to Carter:

> Carter: Either the data feed from QS is stale or the data push is stale - happens from time to time, derivative rates change slowly enough that impact is minimal when things get stale.

This assumption does not hold:
https://github.com/securesecrets/shadejs/blob/730b92030e7ea5dc2e01693d5dffde8d383cc7e2/src/contracts/services/swap.ts#L199

**To Reproduce**
Attempt to call `stableSwapToken0for1` on the **ATOM+qATOM** pool.

**Expected behavior**
Ideally, shadejs should throw a descriptive error message, or even a typed error class, so that callers can handle the exception and so that developers can understand the issue (rather than the cryptic TypeError).

Additionally, it might be worth mentioning this edge case in the developer documentation.

**Screenshots**

```shell
secretcli q wasm query secret1f6kw62rzgn3fwc0jfp7nxjks0l45jv3r6tpc0x '{"get_pair_info":{}}' | jq '.get_pair_info.stable_info'
```

<img width="356" alt="Screenshot 2024-01-20 at 12 57 57" src="https://github.com/securesecrets/shadejs/assets/1456400/10a7fafb-db0c-400d-9a42-1ccd4975be09">

**Comment by AustinWoetzel** [comment]
Good catch. The issue with throwing an error is that the rest of the data is still valid, so I wouldn't want to ignore the other pool data just because the price ratio came back null. I will throw an error in the example router to handle this and add to the docs.

**Comment by blake-regalia** [comment]
Just to clarify, I was suggesting throwing an error when swap methods are called and the price ratio is null, e.g., `stableSwapToken0for1`, since otherwise `this.priceOfToken1` will be null and unusable in calculations and cause a vague error be thrown, such as TypeError.
