### ISSUE TITLE
Class method passed as unbound function results in undefined `this`

### ISSUE THREAD

**Issue by blake-regalia** [securesecrets/shadejs#78]
**Describe the bug**

When `this.geometricMeanDoubled` is passed by reference to the `lazyLowerBoundBisect` option:
https://github.com/securesecrets/shadejs/blob/730b92030e7ea5dc2e01693d5dffde8d383cc7e2/src/lib/swap/stableswapCurve/stable.ts#L741

it will later get called as an unbound function, causing `this` to be undefined when it gets called, here:
https://github.com/securesecrets/shadejs/blob/730b92030e7ea5dc2e01693d5dffde8d383cc7e2/src/lib/swap/stableswapCurve/stable.ts#L592

resulting in
```
TypeError: undefined is not an object (evaluating 'this.token1TvlInUnitsToken0')
    at geometricMeanDoubled ...
```

**To Reproduce**
N/A

**Expected behavior**
Should not happen.

**Screenshots**
N/A

**Additional context**

An easy fix would be to bind the function when passed, like so:
```ts
 lazyLowerBoundBisect: this.geometricMeanDoubled.bind(this),
```

**Comment by AustinWoetzel** [comment]
thanks for fix on this one.
